name: C Quality Check and Formatting
on: [push, pull_request]
jobs:
  formatting-check:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format.
      uses: jidicula/clang-format-action@v4.10.2
      with:
        clang-format-version: '15'
        fallback-style: 'Mozilla' # optional
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: ${{ github.actor }}
        author_email: ${{ github.actor }}@users.noreply.github.com
        message: "clang-format code formatting"
        add: "."
        branch: ${{ github.ref }}
